services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ollama_models:/root/.ollama

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "${N8N_PORT:-5678}:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Lisbon
      - TZ=Europe/Lisbon
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/workflows:/workflows
    depends_on:
      - ollama

volumes:
  ollama_models:
    driver: local
  n8n_data:
    driver: local
